<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Nate Lant and Austin Hopkins" />


<title>Effect of Wheelchair Use</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">512 Final Project</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="01_data.html">Introduction</a>
</li>
<li>
  <a href="02_variables.html">Variable Comparison</a>
</li>
<li>
  <a href="03_disability.html">Disability Effect</a>
</li>
<li>
  <a href="04_wheelchair.html">Wheelchair Effect</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Effect of Wheelchair Use</h1>
<h4 class="author">Nate Lant and Austin Hopkins</h4>
<h4 class="date">4/14/2020</h4>

</div>


<p>This section compares different models in predicting the likelihood of employment for users with wheelchairs. The response variable is the <code>worker</code> variable which is employment status, 0 for unemployed and 1 for employed.</p>
<p>At the most basic level, the binomial regression is the same as the odds ratio. The logit is <span class="math inline">\(z\)</span> in <span class="math display">\[  z = \beta_0 + \beta_1*x_1 \]</span></p>
<p>The odds ratio can be calculated using <span class="math inline">\(e^\beta\)</span>. This is not to be confused with the odds, defined as <span class="math inline">\(e^z\)</span>. With odds, we can calculate the probability of getting employed as</p>
<p><span class="math display">\[ P = \frac{e^z}{1+e^z}\]</span></p>
<div id="reduced-model" class="section level2">
<h2>Reduced Model</h2>
<p>The first model will regress worker status on wheelchair usage. This model will calculate the odds of employment if you have a wheelchair compared to not having a wheelchair (odds ratio).</p>
<pre class="r"><code>glm(worker ~ wheelchair, data = mydata1, family = binomial(link=&#39;logit&#39;)) %&gt;%
  summary()</code></pre>
<pre><code>## 
## Call:
## glm(formula = worker ~ wheelchair, family = binomial(link = &quot;logit&quot;), 
##     data = mydata1)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -1.644  -1.644   0.774   0.774   2.030  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  1.052113   0.006133  171.54   &lt;2e-16 ***
## wheelchair  -2.976664   0.082573  -36.05   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 161696  on 139909  degrees of freedom
## Residual deviance: 159501  on 139908  degrees of freedom
## AIC: 159505
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>In this case, <span class="math inline">\(e^(-2.976)\)</span> is 0.051, or 1:20. This states that if you have a wheelchair, you are 20 times more likely to be unemployed. Lets see how this changes with interactions.</p>
</div>
<div id="full-model" class="section level2">
<h2>Full Model</h2>
<pre class="r"><code>glm(worker ~ educ*wheelchair + r_sex*wheelchair + log(inc_cont)*wheelchair + age_bar*wheelchair, 
    data = mydata1, family = &quot;binomial&quot;) %&gt;%
  summary()</code></pre>
<pre><code>## 
## Call:
## glm(formula = worker ~ educ * wheelchair + r_sex * wheelchair + 
##     log(inc_cont) * wheelchair + age_bar * wheelchair, family = &quot;binomial&quot;, 
##     data = mydata1)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.3621  -0.7440   0.5578   0.7428   2.9755  
## 
## Coefficients:
##                           Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)              -5.081029   0.086320 -58.863  &lt; 2e-16 ***
## educ02                    0.528220   0.037204  14.198  &lt; 2e-16 ***
## educ03                    0.732488   0.036579  20.025  &lt; 2e-16 ***
## educ04                    0.860771   0.037688  22.839  &lt; 2e-16 ***
## educ05                    1.031206   0.038842  26.549  &lt; 2e-16 ***
## wheelchair               -3.031867   1.074496  -2.822  0.00478 ** 
## r_sex02                  -0.635188   0.013532 -46.938  &lt; 2e-16 ***
## log(inc_cont)             0.555152   0.007881  70.442  &lt; 2e-16 ***
## age_bar                  -1.015858   0.013465 -75.445  &lt; 2e-16 ***
## educ02:wheelchair        -0.012251   0.463330  -0.026  0.97891    
## educ03:wheelchair         0.186699   0.450097   0.415  0.67829    
## educ04:wheelchair         0.895391   0.467541   1.915  0.05548 .  
## educ05:wheelchair         1.175309   0.475449   2.472  0.01344 *  
## wheelchair:r_sex02        0.576725   0.180863   3.189  0.00143 ** 
## wheelchair:log(inc_cont) -0.028250   0.095869  -0.295  0.76824    
## wheelchair:age_bar        0.284784   0.179054   1.590  0.11172    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 161696  on 139909  degrees of freedom
## Residual deviance: 141446  on 139894  degrees of freedom
## AIC: 141478
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>This shows for example the odds ratio of a wheelchair user who attained education level 5 (graduate or professional degree) is <span class="math inline">\(e^(-3.03+1.03+1.175)\)</span> = 0.438.</p>
<p>This shows that education (with the exception of graduate school) does not affect employment for wheelchair users any differently than for non wheelchair users.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
